config/routes.rb
Rails.application.routes.draw do
  # devise_for :samples
  # devise_for :clients
  # devise_for :users
  devise_for :samples, controllers: {
    sessions:      'samples/sessions',
    passwords:     'samples/passwords',
    registrations: 'samples/registrations'
  }
  devise_for :clients, controllers: {
    sessions:      'clients/sessions',
    passwords:     'clients/passwords',
    registrations: 'clients/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  devise_scope :sample do
    post 'samples/guest_sign_in', to: 'samples/sessions#new_guest'
  end
  devise_scope :client do
    post 'clients/guest_sign_in', to: 'clients/sessions#new_guest'
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # root to: 'kototabis#index'
  resources :demos, only: [:index, :new, :edit, :update, :create, :destroy] do
    collection do
      get 'demos/list'
    end
  end
    get 'demos/home'
    get 'demos/about'
    get 'demos/show'
    get 'demos/schedule'
    get 'demos/search'
    get 'demos/search_words'

  resources :events do #管理画面用
    collection do
      get 'search_words'
      get 'events/search' 
    end
  end 

  resources :tops
    post 'products/add'
  resources :products do
    resources :points
    resources :itinerarys
    resources :events 
  end

  root to: 'demos#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :company_name, :c_kana, :supervisor, :s_kana, :company_address, :tel, :email, presence: true
  # ゲストログイン
  def self.guest
    find_or_create_by!(email: 'client@example.com') do |client|
      client.password = SecureRandom.urlsafe_base64
      # client.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end
end

app/models/demo.rb
class Demo < ApplicationRecord
  attr_accessor :token

  belongs_to :sample, optional: true
  # モジュールを取り込む記述
  extend ActiveHash::Associations::ActiveRecordExtensions
  # アクティブハッシュ用rアソシエーション
  belongs_to_active_hash :num

  validates :token, presence: true, on: :create
  validates :start_time, presence: true
  validates :num_id, presence: true, numericality: { other_than: 0 }
  validates :price, presence: true, numericality: { other_than: 0 }
end

app/models/event.rb
class Event < ApplicationRecord
  attr_accessor :token

  belongs_to :user, optional: true
  belongs_to :client, optional: true
  belongs_to :product, optional: true
  # モジュールを取り込む記述
  extend ActiveHash::Associations::ActiveRecordExtensions
  # アクティブハッシュ用アソシエーション
  belongs_to_active_hash :num

  # バリデーション
  validates :token, presence: true, on: :create
  validates :start_time, presence: true
  validates :num_id, presence: true, numericality: { other_than: 0 }
  validates :price, presence: true, numericality: { other_than: 0 }

  # <ワード検索時の処理>
  def self.search(search)
    if search != ''
      Event.where('price LIKE(?)', "%#{search}%")
    else
      Event.all
    end
  end
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
  belongs_to :product, optional: true
  # Active Storage用アソシエーション
  has_one_attached :image
  validates :title, presence: true
end

app/models/num.rb
class Num < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '1', multiple: 1 },
    { id: 2, name: '2', multiple: 2 },
    { id: 3, name: '3', multiple: 3 },
    { id: 4, name: '4', multiple: 4 },
    { id: 5, name: '5', multiple: 5 },
    { id: 6, name: '6', multiple: 6 },
    { id: 7, name: '7', multiple: 7 },
    { id: 8, name: '8', multiple: 8 },
    { id: 9, name: '9', multiple: 9 },
    { id: 10, name: '10', multiple: 10 },
    { id: 11, name: 'お問い合わせください' }
  ]
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :products, optional: true
  # Active Storage用アソシエーション
  has_one_attached :image
  validates :title, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :client, optional: true
  has_many :point, dependent: :destroy
  has_many :itinerarys, dependent: :destroy
  # cocoonで子フォームを親と一緒に保存するための記述。
  accepts_nested_attributes_for :itinerarys, allow_destroy: true
  # Active Storage用アソシエーション
  has_one_attached :image
  validates :image, :name, :price, :unit, presence: true
end

app/models/producte.rb
class Producte < ApplicationRecord
  belongs_to :client
  # Active Storage用アソシエーション
  has_one_attached :image
end

app/models/sample.rb
class Sample < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #  :recoverable, :rememberable, :validatable, :timeoutable

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |sample|
      sample.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end
  # def self.guest
  #   find_or_create_by!(email: 'guest@example.com') do |user|
  #     user.password = SecureRandom.urlsafe_base64
  #     # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
  #   end
  # end
end

app/models/top.rb
class Top < ApplicationRecord
  belongs_to :client, optional: true
  has_many :product  # , dependent: :destroy
  # Active Storage用アソシエーション
  has_one_attached :image
  # career wave用
  mount_uploader :video_top, VideoUploader
  validates :video_top, :client_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, :kana, :email, :tel, presence: true

  # ゲストログイン
  def self.guest
    find_or_create_by!(email: 'user@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end

  # <ワード検索時の処理>
  def self.search(search)
    if search != ''
      User.where('name LIKE(?)', "%#{search}%")
    else
      User.all
    end
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @client = Client.find(current_client.id) # footer条件分岐のため。どのクライアントか特定する為にcurrent_client.id
    @top = Top.find_by(client_id: @client.id)
    # @products = Product.find(params[:id]) #top/indexでproductのデータを表示させる為。元々レンダーで_product.htmlを表示させる為の定義だった。
    @products = Product.where(client_id: @client.id) # top/indexでproductのデータを表示させる為。
  end

  def new
    @top = Top.new
  end

  def show
    @top = Top.find_by(client_id: params[:id])
    @products =  Product.where(client_id: params[:id])
    @client_id = params[:id]
    session['current.client_id'] = { client: @client_id }
    @client = Client.find(@client_id)
  end

  def create
    @top = Top.new(tops_params)
    if @top.save
      redirect_to new_product_path
    else
      render :new
    end
  end

  def edit
    @client = Client.find(current_client.id) # footer条件分岐のため
    @top = Top.find_by(client_id: @client.id) # データ取得（トップ動画再生と編集データ取得）
    @products = Product.where(client_id: @client.id) # top/indexでproductのデータを表示させる為。
  end

  def update
    top = Top.find(params[:id])
    top.update(tops_params)
    # if top.valid?
    redirect_to edit_top_path
    # else
    # end
  end

  def destroy
    @top = Top.find(params[:id])
    @top.destroy!
    redirect_to root_path
  end

  private

  def tops_params
    params.require(:top).permit(:video_top, :image, :title, :client_id).merge(client_id: current_client.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/itinerarys_helper.rb
module ItinerarysHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/kototabi/index.html.erb
<h1>Kototabi#index</h1>
<!-----ヘッター------>
<div class="header-wrap">
  <div class="header-main">
    <div class="header-left">
      <div class="header-logo-box">
        <%= link_to image_tag("/assets/header-logo"), tops_path, class:"header-logo-img" %>
      </div>
      <div class="header-introduction">
        <ul>
          <li><%=link_to "機能紹介", kototabi_show_about_path %></li>
          <li><%=link_to "サンプルを使う", kototabi_show_path %></li>
        </ul>
      </div>
    </div>
    <div class="header-right">
      <div class="header-right-li">
        <span><%= link_to '試作する', clients_guest_sign_in_path, method: :post %></span>
      </div>
      <div class="header-right-li">
        <%= link_to "新規登録", new_client_registration_path %>
      </div>
      <div class="header-right-li">
        <%= link_to "ログイン", new_client_session_path %>
      </div>
    </div>
  </div>
</div>

<!-----メイン------>
<div class="top">
<!----動画----->
  <div class="top_video_content" >
    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <%= video_tag("kototabi.mp4", class: "top_video", autoplay: true, loop: true, muted: true, alt:"ダミー画像") %>
          <div class="top_hero" >
            <%= image_tag "top-logo.png", class: "top_logo" %>
            <h3 class="top_title">ネットで作るECサイト</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
<!-----区切り------>
  <div class="section">
    <div class="container mb-5">
      <div class="row">
      <%# <h3>ネットでECサイトを作るなら</h3>
      <h3>クリックひとつ簡単作成。顧客・商品管理まできこれ一本</h3> %>
        <h2 class="section col-12">
        <span class="section-name mb-5 border-bottom">sample</span>
        <small>サンプル</small>
        </h2>
      </div>
    </div>
  </div>
<!----商品----->
  <div class="products-container container-fluid">
    <div class="row row-cols-3">
        <div class="products_hero col">
          <%= link_to kototabi_show_path do %>
            <%=image_tag "product_sample3", alt:"商品画像", class:"products_img" %>
            <div class="products_info">
              <p class="products_name">sample</p>
              <p class="products_text"></p>
            </div>
          <% end %>
        </div>
        <div class="products_hero col">
          <%= link_to kototabi_show_path do %>
            <%=image_tag "product_sample.png", alt:"商品画像", class:"products_img" %>
            <div class="products_info">
              <p class="products_name">sample</p>
              <p class="products_text"></p>
            </div>
          <% end %>
        </div>
        <div class="products_hero col">
          <%#= link_to kototabi_index_path do %>
          <%= link_to kototabi_show_path do %>
            <%=image_tag "puroduct_sample2", alt:"商品画像", class:"products_img" %>
            <div class="products_info">
              <p class="products_name">sample</p>
              <p class="products_text"></p>
            </div>
          <% end %>
        </div>
    </div>
  </div>
  <%= render "shared/footer_client" %>
</div>

app/views/kototabi/show_about.erb
<!-----ヘッター------>
<div class="header-wrap">
  <div class="header-main-1">
    <div class="header-left">
      <div class="header-logo-box">
        <%= link_to image_tag("/assets/header-logo2"), tops_path, class:"header-logo-img" %>
      </div>
      <div class="header-introduction-1">
        <ul>
          <li><%=link_to "機能紹介", kototabi_show_about_path %></li>
          <li><%=link_to "サンプルを使う", kototabi_show_path %></li>
        </ul>
      </div>
    </div>
    <div class="header-right">
      <div class="header-right-li-1">
        <span><%= link_to '試作する', clients_guest_sign_in_path, method: :post %></span>
      </div>
      <div class="header-right-li-1">
        <%= link_to "新規登録", new_client_registration_path %>
      </div>
      <div class="header-right-li-1">
        <%= link_to "ログイン", new_client_session_path %>
      </div>
    </div>
  </div>
</div>

<div class="about-wrap">
  <div class="cover">
    <div class="cover-introduction">
      <div class="cover-center">
        <h1 class=font_0>KOTOTABI 機能紹介</h1>
        <div class="cover-text">
          <p>Webサイトの作成と運営に必要な顧客・商品管理機能がここに。</p>
          <p></p>
          <p>KOTOTABI の機能をご紹介します。</p>
        </div>
          <%= link_to new_client_session_path do %>
            <div class="cover-create-button">
              <h3>サイトを作成する</h3>
            </div>
          <% end %>
      </div>
      <div class="cover-br">
      </div>
      <div class="cover-footer">
        <ul><a href=""></a>
          <li class="cover-footer-li-1"><a href="#sec1">クリエイト</a></li>
          <li class="cover-footer-li"><a href="#sec2">アド</a></li>
          <li class="cover-footer-li"><a href="#sec3">エディタ</a></li>
          <li class="cover-footer-li"><a href="#sec4">アドミン</a></li>
        </ul>
      </div>
    </div><%#cover-introduction%>
  </div>

  <div class="about-container">
    <div class="row">
      <div class="about-main">
        <div class="about-main-create">
          <h1>Create 作成する</h1>
            <div class="bout-main-create-text">
              <p>簡単２ステップ。好きな動画や画像を選択するだけ。</p>
              <p>タイトルや紹介文など、運営に必要内容を入力すると、</p>
              <a name="#sec1">
              <p>あなただけのWebサイトが完成ます。</p>
              </a>
            </div>
          画像
        </div>
        <div class="about-main-add">
          <h1>Add 追加</h1>
            <div class="about-main-add-text">
              <p>管理画面へ行き左上のEditerボタンを押すとメニューバーが現れます。</p>
              <a name="sec2">
              <p>増やしたい項目に入力するだけ。</p>
              </a>
            </div>
            画像
        </div>
        <div class="about-main-edit">
          <h1>Edit 編集</h1>
            <div class="about-main-edit-text">
              <p>管理画面から商品のページに進みます。</p>
              <a name="sec3">
              <p>編集したい項目を書き換え、編集ボタンを押すと編集されます。</p>
              </a>
            </div>
            画像
        </div>
        <div class="about-main-admin">
          <h1>Admin 予約管理</h1>
            <div class="about-admin-text">
              <a name="sec4">
              <p>予約管理ボタンを押すと、、、</p>
              </a>
            </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/kototabis/index.html.erb
<h1>Kototabis#index</h1>

<!-----ヘッター------>
<div class="header-wrap">
  <div class="header-main">
    <div class="header-left">
      <div class="header-logo-box">
        <%= link_to image_tag("/assets/header-logo"), tops_path, class:"header-logo-img" %>
      </div>
      <div class="header-introduction">
        <ul>
          <li><%=link_to "機能紹介", kototabis_show_about_path %></li>
          <li><%=link_to "デモを使う", kototabis_show_top_path %></li>
        </ul>
      </div>
    </div>
    <div class="header-right">
      <div class="header-right-li">
        <span><%= link_to '試作する', clients_guest_sign_in_path, method: :post %></span>
      </div>
      <div class="header-right-li">
        <%= link_to "新規登録", new_client_registration_path %>
      </div>
      <div class="header-right-li">
        <%= link_to "ログイン", new_client_session_path %>
      </div>
    </div>
  </div>
</div>

<!-----メイン------>
<div class="top">
<!----動画----->
  <div class="top_video_content" >
    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <%= video_tag("kototabi.mp4", class: "top_video", autoplay: true, loop: true, muted: true, alt:"ダミー画像") %>
          <div class="top_hero" >
            <%= image_tag "top-logo.png", class: "top_logo" %>
            <h3 class="top_title">ネットで作るECサイト</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
<!-----区切り------>
  <div class="section">
    <div class="container mb-5">
      <div class="row">
      <%# <h3>ネットでECサイトを作るなら</h3>
      <h3>クリックひとつ簡単作成。顧客・商品管理まできこれ一本</h3> %>
        <h2 class="section col-12">
        <span class="section-name mb-5 border-bottom">sample</span>
        <small>サンプル</small>
        </h2>
      </div>
    </div>
  </div>
<!----商品----->
  <div class="products-container container-fluid">
    <div class="row row-cols-3">
        <div class="products_hero col">
          <%= link_to kototabis_show_top_path do %>
            <%=image_tag "product_sample3", alt:"商品画像", class:"products_img" %>
            <div class="products_info">
              <p class="products_name">sample</p>
              <p class="products_text"></p>
            </div>
          <% end %>
        </div>
        <div class="products_hero col">
          <%= link_to kototabis_show_top_path do %>
            <%=image_tag "product_sample.png", alt:"商品画像", class:"products_img" %>
            <div class="products_info">
              <p class="products_name">sample</p>
              <p class="products_text"></p>
            </div>
          <% end %>
        </div>
        <div class="products_hero col">
          <%= link_to kototabis_show_top_path do %>
            <%=image_tag "puroduct_sample2", alt:"商品画像", class:"products_img" %>
            <div class="products_info">
              <p class="products_name">sample</p>
              <p class="products_text"></p>
            </div>
          <% end %>
        </div>
    </div>
  </div>
  <%= render "shared/footer_client" %>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <div class="footer">
    <div class='client-wrap' >
      <% if client_signed_in? %>
        <div class="client-admin-if-login-box">
          <div class="company-info">
            <ul>
              <li>会社名<span>:</span><%= current_client.company_name %></li>
              <li>所在<span>:</span><%#= current_client.company_address %></li>
              <li>e-mail<span>:</span><%= current_client.email %></li>
              <li>TEL<span>:</span><%= current_client.tel %></li>
            </ul>
          </div>
          <!--画像の有無--->
          <div class="client-menu">
            <ul>
              <li>
                <p>Admin</p>
              </li>
              <% if @top == nil %>
                <li>
                  <%= link_to "新規top画面を作成する", new_top_path, class:"client-menu-li" %>
                </li>
              <% else %>
                <li>
                  <%= link_to "管理者画面に行く", edit_top_path(@top.id), class:"client-menu-li" %>
                </li>
                <li>
                  <%= link_to "予約管理画面", events_path, class:"client-menu-li" %>
                </li>
              <% end %>
              <li>
                <%= link_to 'ログアウト', destroy_client_session_path, method: :delete, class:"client-menu-li" %>
              </li>
            </ul>
          </div>
        </div><!---client-admin-if-login-box--->
      <% else %>
        <div class="client-no-account-box">
          <div class="company-info">
            <ul>
              <li>会社名<span>:</span>KOTOTABI</li>
              <li>所在<span>:</span>京都府京都市上京区京都御苑</li>
              <li>E-mail<span>:</span>kototabi@xxx.com</li>
              <li>TEL<span>:</span>090-1234-5678</li>
            </ul>
          </div>
          <div class="client-admin-no-account">
            <ul>
              <div id="app3">
                <li>
                  <div class="admin-button-box" v-on:click='ActiveBtn=!ActiveBtn'>
                    <p>Admin</p>
                  </div>
                </li>
                  <transition name="editor-side">
                    <div v-show="ActiveBtn">
                      <li><%= link_to "新規登録する", new_client_registration_path, class:"client-about-sign-up" %></li>
                      <li><%= link_to "ログイン", new_client_session_path, class:"client-about-sign-up" %></li>
                    </div>
                  </transition>
              </div><!--app3-->
            </ul>
          </div><!--client-admin-noaccount"-->
        </div><!--client-no-account-box-->
      <% end %>
      <div class="footer-logo-box">
        <img src="/assets/footer-logo.png" alt="footer-logo.png" class="footer-logo">
      </div>
    </div><!--client-wrap-->
  </div><!--footer-->

app/views/shared/_footer_client.html.erb
  <div class="footer">
    <div class="client-wrap" >
      <% if @client != nil %> 
        <div class="client-admin-if-login-box">
          <div class="company-info">
            <ul>
              <li>会社名<span>:</span><%= @client.company_name %></li>
              <li>所在<span>:</span><%= @client.company_address %></li>
              <li>メール<span>:</span><%= @client.email %></li>
              <li>TEL<span>:</span><%= @client.tel %></li>
            </ul>
          </div>
          <!--画像の有無--->
          <% if client_signed_in? %>
            <div class="client-menu">
              <ul>
                <li>
                  <p>Admin</p>
                </li>
                <% if @top == nil %>
                  <li>
                    <%= link_to "サイトを作成する", new_top_path, class:"client-menu-li" %>
                  </li>
                <% else %>
                  <li>
                    <%= link_to "編集画面", edit_top_path(@top.id), class:"client-menu-li" %>
                  </li>
                  <li>
                    <%= link_to "予約管理", events_path, class:"client-menu-li" %>
                  </li>
                <% end %>
                  <li>
                    <%#= link_to "戻る", tops_path(@top.id), class:"client-menu-li" %>
                    <%= link_to "戻る", tops_path, class:"client-menu-li" %>
                  </li>
                  <li>
                    <%= link_to 'ログアウト', destroy_client_session_path, method: :delete, class:"client-menu-li" %>
                  </li>
              </ul>
            </div>
          <% else %>
            <div class="client-menu">
              <div class="client-admin-no-account">
                  <div id="app3">
                    <ul>
                      <li>
                        <div class="admin-button-box" v-on:click='ActiveBtn=!ActiveBtn'>
                          <p>Admin</p>
                        </div>
                      </li>
                        <transition name="editor-side">
                          <div v-show="ActiveBtn">
                            <li><%= link_to "新規登録する", new_client_registration_path, class:"client-about-sign-up" %></li>
                            <li><%= link_to 'ゲストログイン', clients_guest_sign_in_path, method: :post, class:"client-about-sign-up" %></li>
                            <li><%= link_to "ログイン", new_client_session_path, class:"client-about-sign-up" %></li>
                          </div>
                        </transition>
                    </ul>
                  </div><!--app3-->
              </div><!--client-admin-noaccount"-->
            </div>
          <% end %>
        </div><!---client-admin-if-login-box--->
      <% else %>
        <div class="client-no-account-box">
          <div class="company-info">
            <ul>
              <li>会社名<span>:</span>CODELESS INC.</li>
              <li>所在<span>:</span>京都府京都市上京区京都御苑△△</li>
              <li>メール<span>:</span>codeless@xxx.com</li>
              <li>TEL<span>:</span>050-5362-5645</li>
            </ul>
          </div>
          <div class="client-admin-no-account">
            <div id="app3">
              <ul>
                <li>
                  <div class="admin-button-box" v-on:click='ActiveBtn=!ActiveBtn'>
                    <p>Admin</p>
                  </div>
                </li>
                  <transition name="editor-side">
                    <div class="client-about-sign-up" v-show="ActiveBtn">
                      <li><%= link_to '試作する', clients_guest_sign_in_path, method: :post %></li>
                      <li><%= link_to "新規登録する", new_client_registration_path %></li>
                      <li><%= link_to "ログイン", new_client_session_path %></li>
                    </div>
                  </transition>
              </ul>
            </div><!--app3-->
          </div><!--client-admin-noaccount"-->
        </div><!--client-no-account-box-->
      <% end %>
      <div class="footer-logo-box">
        <%#= image_tag "codeless-haeder-ogo.png", alt: "フッター画像", class: "footer-logo" %>
      </div>
    </div><!--client-wrap-->
  </div><!--footer-->
  
<%= javascript_pack_tag 'menu_vue' %>

app/views/shared/_footer_demo.html.erb
  <div class="footer">
    <div class="footer-demo">
      <div class="client-admin-if-login-box">
        <div class="company-info">
          <ul>
            <li>会社名<span>:</span>◯◯◯◯株式会社</li>
            <li>所在<span>:△△△県□□□市</span></li>
            <li>メール<span>:xxxx@kototabi.com</span></li>
            <li>TEL<span>:</span>0120-123-1234</li>
          </ul>
        </div>
      </div>
      <div class="client-menu">
        <ul>
          <li>
            <p>Admin</p>
          </li>
          <li>
            <%= link_to "予約管理", demos_schedule_path, class:"client-menu-li" %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_sample_session_path, method: :delete, class:"client-menu-li" %>
          </li>
        </ul>
      </div>
    </div>
    <div class="footer-logo-box">
      <%#= image_tag "sample_logo.png", alt: "サンプルロゴ.png", class:"footer-logo" %>
    </div>
  </div><!--footer-->

app/views/shared/_header.html.erb
<div class="header-wrap">
  <div class="header-main">
    <div class="header-left">
      <div class="header-logo-box">
        <%= link_to tops_path do %>
          <%= image_tag "codeless-haeder-ogo.png" %>
          <%#= link_to image_tag(@client.logo), tops_path %>
        <% end %>
      </div>
    </div>
    <div class="header-menu">
    </div>
  </div>
</div>

app/views/shared/_header_demo.html.erb
<!-----ヘッター------>
<div class="header-wrap">
  <div class="header-main">
    <div class="header-left">
      <div class="header-logo-box">
        <%= link_to  root_path do %>
          <%= image_tag "codeless-haeder-ogo.png", class:"header-logo-img" %>
        <% end %>
      </div>

      <div class="header-introduction">
        <ul>
          <li><%=link_to "無料デモを使う", samples_guest_sign_in_path, method: :post %></a>
            <%# <ul>
              <li><a href="#">Sub-menu01</a></li>
              <li><a href="#">Sub-menu02</a></li>
              <li><a href="#">Sub-menu03</a></li>
            </ul> %>
          </li>
          <li><%= link_to 'デモを編集する', clients_guest_sign_in_path, method: :post %></li>
          <li><%=link_to "機能紹介", demos_about_path  %></li>
          <li><%=link_to "導入企業一覧", demos_list_demos_path %></li>
          <%# <li><%=link_to "sign_in", new_sample_registration_path%></li>
        </ul>
      </div>
    </div>
    <div class="header-right">
      <div class="header-right-li">
        <%= link_to "新規登録", new_client_registration_path %>
      </div>
      <div class="header-right-li">
        <%= link_to "ログイン", new_client_session_path %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header_demo_user.html.erb
<div class="header-wrap">
  <div class="header-main">
    <div class="header-logo-box">
      <%= link_to image_tag("header-logo.png"), demos_path%>
    </div>
    <div class="header-menu">
    </div>
  </div>
</div>

app/views/shared/_header_user.html.erb
<div class="header-wrap">
  <div class="header-main">
    <div class="header-left">
      <div class="header-logo-box">
        <%= link_to image_tag("header-logo.png"), top_path(@product.client.id) %>
        <%#= link_to image_tag(@client.logo), tops_path %>
      </div>
    </div>
    <div class="header-menu">
    </div>
  </div>
</div>