config/routes.rb
Rails.application.routes.draw do
  # devise_for :samples
  # devise_for :clients
  # devise_for :users
  devise_for :samples, controllers: {
    sessions:      'samples/sessions',
    passwords:     'samples/passwords',
    registrations: 'samples/registrations'
  }
  devise_for :clients, controllers: {
    sessions:      'clients/sessions',
    passwords:     'clients/passwords',
    registrations: 'clients/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  devise_scope :sample do
    post 'samples/guest_sign_in', to: 'samples/sessions#new_guest'
  end
  devise_scope :client do
    post 'clients/guest_sign_in', to: 'clients/sessions#new_guest'
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # root to: 'kototabis#index'
  resources :demos, only: [:index, :new, :edit, :update, :create, :destroy] do
    collection do
      get 'demos/list'
    end
  end
    get 'demos/home'
    get 'demos/about'
    get 'demos/show'
    get 'demos/schedule'
    get 'demos/search'
    get 'demos/search_words'

  resources :events do #管理画面用
    collection do
      get 'search_words'
      get 'events/search' 
    end
  end 

  resources :tops
    post 'products/add'
  resources :products do
    resources :points
    resources :itinerarys
    resources :events 
  end

  root to: 'demos#home'
end

app/models/demo.rb
class Demo < ApplicationRecord
  attr_accessor :token

  belongs_to :sample, optional: true
  # モジュールを取り込む記述
  extend ActiveHash::Associations::ActiveRecordExtensions
  # アクティブハッシュ用rアソシエーション
  belongs_to_active_hash :num

  validates :token, presence: true, on: :create
  validates :start_time, presence: true
  validates :num_id, presence: true, numericality: { other_than: 0 }
  validates :price, presence: true, numericality: { other_than: 0 }
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  before_action :search_product, only: [:schedule, :search]

  def home
  end

  def about
  end

  def index
    @sample = Sample.find(current_sample.id)
  end

  def new
    @demo = Demo.new(demo_params)
  end

  def create
    @demo = Demo.new(demo_create_params)
    if @demo.valid?
      @demo.save
    else
      render :new
    end
  end

  def show
  end

  def schedule
    @demos = Demo.all
    # @demo_yaer = Demo.ransack(start_time_cont: [1]).result.to_sql
    # @demo_date = Demo.select("start_time_date").distinct
    set_demo_column
  end

  def edit
    @demo = Demo.find(params[:id])
  end

  def update
    demo = Demo.find(params[:id])
    demo.update!(demo_create_params)
    redirect_to edit_demo_path(demo.id)
  end

  def destroy
    demo = Demo.find(params[:id])
    demo.destroy
    redirect_to demos_schedule_path(demo.id)
  end

  def list
    @clients = Client.all
  end

  def search
    @results = @d.result
  end

  def search_words
  end

  private

  def demo_params
    # params.require(:demo).permit(:sample_name, :sample_kana, :sample_email, :sample_tel, :sample_product_name, :price, :num_id, :start_time, :sample_id).merge(sample_id: current_sample.id, token: params[:token])
    params.permit(:sample_name, :sample_kana, :sample_email, :sample_tel, :sample_product_name, :price, :num_id, :start_time, :sample_id).merge(
      sample_id: current_sample.id, token: params[:token]
    )
  end

  def demo_create_params
    params.require(:demo).permit(:sample_name, :sample_kana, :sample_email, :sample_tel, :sample_product_name, :price, :num_id, :start_time, :sample_id).merge(
      sample_id: current_sample.id, token: params[:token]
    )
  end

  def search_product
    @d = Demo.ransack(params[:q]) # 検索オブジェクトを生成
  end

  def set_demo_column
    @demo_name = Demo.select('sample_product_name').distinct
    # @demo_date = Demo.select("start_time_name").distinct# 重複なくnameカラムのデータを取り出す
  end
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/views/demos/about.html.erb
<!-----ヘッター------>
<div class="header-wrap">
  <div class="header-main-1">
    <div class="header-left">
      <div class="header-logo-box">
        <%= link_to root_path, class:"header-logo-img" do %>
          <%= image_tag "codeless-haeder-ogo.png", class:"header-logo-img" %>
        <% end %>
      </div>
      <div class="header-introduction-1">
        <ul>
          <li><%= link_to "無料デモを使う", samples_guest_sign_in_path, method: :post %></li>
          <li><%= link_to 'デモを編集する', clients_guest_sign_in_path, method: :post %></li>
          <li><%= link_to "機能紹介", demos_about_path  %></li>
          <li><%= link_to "導入企業一覧", demos_list_demos_path %></li>
      </div>
    </div>
    <div class="header-right">
      <div class="header-right-li-1">
        <%= link_to "新規登録", new_client_registration_path %>
      </div>
      <div class="header-right-li-1">
        <%= link_to "ログイン", new_client_session_path %>
      </div>
    </div>
  </div>
</div>
<div class="about-wrap">
  <div class="cover">
    <div class="cover-introduction">
      <div class="cover-center">
        <h1 class=font_0>CODELESS 機能紹介</h1>
        <div class="cover-text">
          <p>ECサイトの作成と運営に必要な顧客・商品管理機能がここに。</p>
          <p></p>
          <p>CODELESSの機能をご紹介します。</p>
        </div>
        <div class="cover-demo-box">
          <%= link_to samples_guest_sign_in_path, method: :post  do %>
            <div class="cover-demo-button">
              <h3>無料デモを使う</h3>
            </div>
          <% end %>
          <%= link_to clients_guest_sign_in_path, method: :post  do %>
            <div class="cover-demo-button">
              <h3>デモを編集する</h3>
            </div>
          <% end %>
        </div>
      </div>
      <div class="cover-br">
      </div>
      <div class="cover-footer">
        <ul><a href=""></a>
          <li class="cover-footer-li-1"><a href="#sec1">Create</a></li>
          <li class="cover-footer-li"><a href="#sec2">Add</a></li>
          <li class="cover-footer-li"><a href="#sec3">Edit</a></li>
          <li class="cover-footer-li"><a href="#sec4">Admin</a></li>
        </ul>
      </div>
    </div><%#cover-introduction%>
  </div>

  <div class="about-container">
    <div class="row">
      <div class="about-main">
        <div class="about-main-box">
          <h1>How to use 操作方法</h1>
          <div class="about-main-box-text">
            <h5>〜デモを使った予約〜</h5>
            <p>１、トップページより「無料デモを使う」をクリックして、次のページで商品を選択します。右の予約フォームで人数と日付をお選びください。</p>
            <p>２、予めテストカード情報を入力しておりますので「予約する」をクリックしてください。</p>
            <h5>〜デモを使った予約（顧客）管理〜</h5>
            <p>１、トップページより「無料デモを使う」をクリックして、次のページで画面右下の「予約管理」をクリックしてください。</p>
            <p>２、カレンダー上の予約者をクリックすると対象者の詳細ページへ遷移します。そこで予約情報の編集及び削除が行えます。</p>
            <p>３、「予約管理」ページより検索が行えます。「商品で検索」で対象の商品を選択し「検索」をクリック対象の商品を選択してる対象者が表示されます。</p>
            <h5>〜デモを使ったECサイト編集〜</h5>
            <p>１、トップページより「デモを編集する」をクリックして、次のページで「Editor」ボタンを押します。</p>
            <p>２、メニューバーが表示されますので、必要事項を入力して「編集する」もしくは「作成する」ボタンを押してください。</p>
            <h5>〜クライアントとしてECサイトを作成する場合〜</h5>
            <p>１、トップページより場面右上の新規登録ボタンをクリックしてください。</p>
            <p>２、「トップ画面作成」ページへ遷移しますので動画や必要事項を入力して「作成する」をクリックしてください。</p>
            <p>３、「商品の作成」ページへ遷移しますので画像や商品の詳細を入力して「作成する」をクリックしてください。</p>
            <p>４、作成が完了すると自動的に編集ページに遷移してします。商品の追加を行うときは左上の「Editor」ボタンをクリックして追加または編集を行ってください。</p>
          </div>
        </div>
        <div class="about-main-box">
          <a name="sec1"><h1>Create 作成する</h1><a>
          <div class="about-main-box-text">
            <p>簡単２ステップ。好きな動画や画像を選択するだけ。</p>
            <p>タイトルや紹介文など、運営に必要内容を入力すると、</p>
            <p>あなただけのWebサイト・ECサイトが完成ます。</p>
          </div>
        </div>
        <div class="about-main-box">
          <a name="sec2"><h1>Add 追加</h1></a>
          <div class="about-main-box-text">
            <p>管理画面へ行き左上のEditerボタンを押すとメニューバーが現れます。</p>
            <p>増やしたい項目に入力するだけ。</p>
          </div>
        </div>
        <div class="about-main-box">
          <a name="sec3"><h1>Edit 編集</h1></a>
          <div class="about-main-box-text">
            <p>管理画面から商品のページに進みます。</p>
            <p>編集したい項目を書き換え、編集ボタンを押すと編集されます。</p>
          </div>
        </div>
        <div class="about-main-box">
          <a name="sec4"><h1>Admin 予約管理</h1></a>
          <div class="about-main-box-text">
            <p>予約管理ボタンを押すと、カレンダーの画面に遷移します。</p>
            <p>予約があれば予定が入りクリックすると編集が可能です。</p>
            <p>また、検索機能で絞り込む事も可能です。</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer_client" %>

app/views/demos/create.html.erb
<%= render "shared/header_demo_user" %>

<div class="done-wrap">
    <div class="done-container">
      <div class="done-box">
        <h1>ご予約完了しました。</h1>
        <p>ありがとうございます。<br>
          ご予約が完了しました。<br>
          確認のメールをお送りしましたので、予約内容を必ずご確認ください。
        </p>
        <div class="back-container">
          <div class="back-container-box">
            <%= link_to "トップへ戻る", samples_guest_sign_in_path, method: :post, class:"btn btn-default back-button" %>
          </div>
        </div>
      </div>
    </div>
  <!------フッター------>
  <%= render "shared/footer_demo" %>
</div>

app/views/demos/destroy.html.erb
<h1>Demos#destroy</h1>
<p>Find me in app/views/demos/destroy.html.erb</p>

app/views/demos/edit.html.erb
<!-----ヘッター----->
<%= render "shared/header_demo_user" %>

<div class="edit-wrap">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">名前</th>
        <th scope="col">人数</th>
        <th scope="col">商品名</th>
        <th scope="col">金額</th>
        <th scope="col">参加日</th>
        <th scope="col">Email</th>
        <th scope="col">TEL</th>
        <th scope="col">オプション</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
    <tr>
      <%= form_with(model: @demo, url:demo_path, method: :PATCH, local: true) do |f| %>
        <tr>
          <td><%= f.text_field :sample_name %></td>
          <td><%= f.collection_select(:num_id, Num.all, :id, :name, {}, {class:"#", id:"#"}) %></td>
          <td><%= f.text_field :sample_product_name %></td>
          <td><%= f.text_field :price %></td>
          <td><%= f.text_field :start_time %></td>
          <td><%= f.text_field :sample_email %></td>
          <td><%= f.text_field :sample_tel %></td>
          <td><%= f.submit "保存する" %></td>
      <% end %>
          <td><%= button_to "削除する", demo_path(@demo.id), method: :delete, class:"#" %></td>
        </tr>
    </tr>
    </tbody>
    <br>
  </table>
  <%= link_to '管理画面へ戻る', demos_schedule_path, class: 'a-back btn' %>
</div>

app/views/demos/home.html.erb
<!-----ヘッター------>
<%= render "shared/header_demo" %>
<!-----メイン------>
<div class="top">
<!----動画----->
  <div class="top_video_content" >
    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <%= video_tag("codeless.mp4", class: "top_video", autoplay: true, loop: true, muted: true, alt:"ダミー画像") %>
          <div class="top_hero">
            <%#= image_tag "codeless-top-logo.png", class: "top_logo" %>
            <h3 class="top_title"></h3>
          </div>
        </div>
      </div>
    </div>
  </div>
<!-----区切り------>
  <div class="section-wrap">
    <div class="section">
      <div class="section-text">
        <h3>CODE LESSでWebサイト・ECサイトを作る。</h3>
        <h3>クリックひとつ簡単作成。顧客・商品管理までこれ一本。</h3>
        <h3>もう、コードを書く必要はありませ。</h3>
      </div>
      <h2 class="section-sample">
        <span class="section-name">sample</span>
        <hr>
        <small>サンプル</small>
      </h2>
    </div>
  </div>
<!----商品----->
  <div class="products-container container-fluid">
    <div class="row row-cols-3">
      <div class="products_hero col">
        <div class="hover-product">
          <%= link_to samples_guest_sign_in_path, method: :post do %>
            <%=image_tag "product_sample3.png", alt:"商品画像", class:"products_img" %>
            <div class="products_info">
              <p class="products_name">sample</p>
              <p class="products_text">title/title/title/title</p>
            </div>
          <% end %>
        </div><%#hover-product%>
      </div>
      <div class="products_hero col">
        <div class="hover-product">
          <%= link_to samples_guest_sign_in_path, method: :post do %>
            <%=image_tag "product_sample1.png", alt:"商品画像", class:"products_img" %>
            <div class="products_info">
              <p class="products_name">sample</p>
              <p class="products_text">title/title/title/title</p>
            </div>
          <% end %>
        </div><%#hover-product%>
      </div>
      <div class="products_hero col">
        <div class="hover-product">
          <%= link_to samples_guest_sign_in_path, method: :post do %>
            <%=image_tag "puroduct_sample2.png", alt:"商品画像", class:"products_img" %>
            <div class="products_info">
              <p class="products_name">sample</p>
              <p class="products_text">title/title/title/title</p>
            </div>
          <% end %>
        </div><%#hover-product%>
      </div>
    </div>
  </div>
  <%= render "shared/footer_client" %>
</div>

app/views/demos/index.html.erb
<div class="top">
  <!--------メニュー--------->
  <div class="menu-wrap">
    <div id="app1">
      <div class="hamburger_btn" v-on:click='ActiveBtn=!ActiveBtn'>
        <span class="line line_01" v-bind:class="{'btn_line01':ActiveBtn}"></span>
        <span class="line line_02" v-bind:class="{'btn_line02':ActiveBtn}"></span>
        <span class="line line_03" v-bind:class="{'btn_line03':ActiveBtn}"></span>
      </div>
      <!--サイドバー-->
      <transition name="menu">
        <div class="menu" v-show="ActiveBtn">
          <div class='user-conf' >
            <div class="user-sin-login">
              <h2>デモメニュー</h2>
              <p>
                <%= link_to samples_guest_sign_in_path, method: :post do%>
                  <%= @sample.name %>
                <% end %>
              </p>
              <p>
                <%= link_to "予約管理", demos_schedule_path%>
              </p>
              <p>
                <%=link_to "ログアウト", destroy_sample_session_path, method: :delete %>
              </p>
            </div>
          </div>
          <!----サイドバー商品名----->
          <div class="main-product">
              <ul>
                <li>
                  <%= link_to "サンプル", demos_show_path %>
                </li>
                <li>
                  <%= link_to "サンプル", demos_show_path %>
                </li>
                <li>
                  <%= link_to "サンプル", demos_show_path %>
                </li>
              </ul>
          </div>
        </div>
      </transition>
    </div>
  </div>
  <!----動画----->

    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <%= video_tag("kototabi.mp4", class: "top_video", autoplay: true, loop: true, muted: true, alt:"ダミー画像") %>
          <div class="top_hero" >
            <%= image_tag "top-logo.png", class: "top_logo" %>
            <h3 class="top_title">KYOTO TOUR</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
<!----商品----->
  <div class="products-container container-fluid">
    <div class="row row-cols-3">
        <div class="products_hero col">
          <div class="hover-product">
            <%= link_to demos_show_path do %>
              <%=image_tag "gojyunoto_b.jpg", alt:"商品画像", class:"products_img" %>
              <div class="products_info">
                <p class="products_name">京都ツアー</p>
                <p class="products_text">sample/sample/sample</p>
              </div>
            <% end %>
          </div>
        </div>
        <div class="products_hero col">
          <div class="hover-product">
            <%= link_to demos_show_path do %>
              <%=image_tag "tatumibashi.jpg", alt:"商品画像", class:"products_img" %>
              <div class="products_info">
                <p class="products_name">京都ツアー</p>
                <p class="products_text">sample/sample/sample</p>
              </div>
            <% end %>
          </div>
        </div>
        <div class="products_hero col">
          <div class="hover-product">
            <%= link_to demos_show_path do %>
              <%=image_tag "IMG_3159.jpg", alt:"商品画像", class:"products_img" %>
              <div class="products_info">
                <p class="products_name">京都ツアー</p>
                <p class="products_text">sample/sample/sample</p>
              </div>
            <% end %>
          </div>
        </div>
    </div>
  </div>

<!------フッター------>
<%= render "shared/footer_demo" %>
</div>

<%= javascript_pack_tag 'menu_vue' %>

app/views/demos/list.html.erb
<%= render "shared/header_demo" %>

<div class="list_wrap">
  <div class="company-list">
    <h1>導入企業一覧</h1>
    <div class="row">
      <div class="list-main">
        <p>CODELESSを導入してる企業様をご紹介します。</p>
        <div class="list-name">
          <% @clients.each do |client| %>
            <li>
              <%= link_to top_path(client.id) do %>
                <%= client.company_name %>
              <% end %>
            </li>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer_logo" %>

app/views/demos/new.html.erb
<%= render "shared/header_demo_user" %>

<div class="conf-wrap">
  <div class="conf-container container">
    <div class="conf-content">
      <div class="pay-content">
        <%= form_with model: @demo, url:demos_path, id: 'demo-charge-form', local: true do |f| %>
          <%= render 'shared/error_messages', model: f.object %>
          <%= f.hidden_field :sample_name, value:current_sample.name %>
          <%= f.hidden_field :sample_kana, value:current_sample.kana %>
          <%= f.hidden_field :sample_email, value:current_sample.email %>
          <%= f.hidden_field :sample_tel, value:current_sample.tel %>
          <%= f.hidden_field :sample_product_name, value:current_sample.product_name %>
          <%= f.hidden_field :num_id, value:@demo.num.id %>
          <%= f.hidden_field :start_time, value:@demo.start_time %>
          <%= f.hidden_field :price, value:@demo.price %>
          <%# 決済機能 %>
          <div class='pay-form-box'>
            <h1>お支払い</h1>
            <div class='pay-form'>
              <div class='card-num'>
                <h4>カード番号</h4>
                <%= f.text_field :number, class:"input-expiration-number", id:"number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
                <%#= f.text_field :number, value:"4242424242424242", class:"input-expiration-number", id:"number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
              </div>
              <div class='input-expiration-date-wrap'>
                <h4>有効期限</h4>
                <div class="input-expiration-date-box">
                  <li><%= f.text_field :exp_month, class:"input-expiration-date", id:"exp_month", placeholder:"例)1" %><span class="expiration-date">月</span></li>
                  <li><%= f.text_field :exp_year, class:"input-expiration-date", id:"exp_year", placeholder:"例)24" %><span class="expiration-date">年</span></li>
                  <li><%#= f.text_field :exp_month, value:"1", class:"input-expiration-date", id:"exp_month", placeholder:"例)1" %>
                  <%# <span class="expiration-date">月</span></li> %>
                  <li><%#= f.text_field :exp_year, value:"24", class:"input-expiration-date", id:"exp_year", placeholder:"例)24" %>
                  <%# <span class="expiration-date">年</span></li> %>
                </div>
              </div>
              <div class="input-expiration-s">
                <h4>セキュリティコード</h4>
                <%#= f.text_field :cvc, value:"123", class:"input-cvc", id:"cvc", placeholder:"カード背面の番号", maxlength:"3" %>
                <%= f.text_field :cvc,  class:"input-cvc", id:"cvc", placeholder:"カード背面の番号", maxlength:"3" %>
              </div>
              <%# <p>※カード情報は予め入力しております。</p>
              <p>そのまま予約ボタンを押してください。</p> %>
              
              <div class='pay-button'>
                <p><%= f.submit "予約する", class:"pay-submit" %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="conf-title-box">
        <h1>内容の確認</h1>
        <div class="conf-title">
          <p>名前: <%= current_sample.name %>様</p>
          <p>商品名: <%= current_sample.product_name %></p>
          <p>参加人数: <%= @demo.num.name %></p>
          <p>ご希望日: <%= @demo.start_time %></p>
          <p>合計金額: ¥<span><%= @demo.price %></span></p>
        </div>
      </div>
    </div>
  </div>
  <%= render "shared/footer_demo" %>
</div>

app/views/demos/schedule.html.erb
<!-----ヘッター----->
<%= render "shared/header_demo_user" %>

<div class="schedule-wrap">
  <div class="search">
    <div class="search-box">
      <h3>商品で検索</h3>
      <%= search_form_for @d, url: demos_search_path do |f| %>
        <%= f.collection_select :sample_product_name_eq, @demo_name, :sample_product_name, :sample_product_name,  include_blank: '指定なし' %>
        <%= f.submit '検索' %>
      <% end %>
    </div>
    <div class="search-box">
      <%# <h3>日付で検索</h3> %>
      <%#= search_form_for @d, url: demos_search_path do |f| %>
        <%#= f.collection_select :start_time_eq, @demos, :start_time, :start_time,  include_blank: '指定なし' %>
        <%#= f.submit '検索' %>
      <%# end %>
      <%#= search_form_for @d, url: demos_search_path do |f| %>
        <%#= f.collection_select :start_time, @demo_yaer, :start_time, :start_time,  include_blank: '指定なし' %>
        <%#= f.submit '検索' %>
      <%# end %>
    </div>
    <div class="search-box">
      <%# <h3>名前検索</h1> %>
      <%#= form_with(url: search_words_events_path, local: true, method: :get, class: "#") do |form| %>
        <%# <label>名前</label> %>
        <%#= form.text_field :keyword, placeholder: "名前で検索する", class: "#" %>
        <%#= form.submit "検索", class: "#" %>
      <%# end %>
    </div>
  </div>

  <!---カレンダー-->
  <%= month_calendar events: @demos do |date, demos| %>
    <%= date.day %>

  <!----イベントー---->
    <ul class="event-list">
      <% demos.each do |demo| %>
      <li class="list">
        <%= link_to edit_demo_path(demo.id) do %>
          <%= demo.sample_name %>
          <%= demo.num.name %><span>人</span>
          <%= demo.sample_product_name %>
        <% end %>
      </li>
    </ul>
    <% end %>
  <% end %>
</div>

  <!------フッター------>
  <%= render "shared/footer_demo" %>
  </div><!--footer-->

app/views/demos/search.html.erb
<!-----ヘッター----->
<%= render "shared/header_demo_user" %>

<div class="edit-wrap">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">商品名</th>
        <th scope="col">参加日</th>
        <th scope="col">名前</th>
        <th scope="col">カナ</th>
        <th scope="col">人数</th>
        <th scope="col">金額</th>
        <th scope="col">Email</th>
        <th scope="col">TEL</th>
        <th scope="col">予約日</th>
        <th scope="col">オプション</th>
      </tr>
    </thead>
    <tbody>
    <tr>
      <h1>検索結果</h1>
      <% if @results.length !=0 %>
        <% @results.each do |result| %>
        <tr>
          <td><%= result.id %></td>
          <td><%= result.sample_product_name %></td>
          <td><%= result.start_time %></td>
          <td><%= result.sample_name %></td>
          <td><%= result.sample_kana %></td>
          <td><%= result.num_id %></td>
          <td><%= result.price %></td>
          <td><%= result.sample_email %></td>
          <td><%= result.sample_tel %></td>
          <td><%= result.created_at %></td>
          <td><%= button_to "編集", edit_demo_path(result.id), method: :get, class:"search-edit-button" %></td>
      <% end %>
      <% else %>
        該当しません
      <% end %>
    </tr>
    </tbody>
    <br>
  </table>
  <%= link_to '管理画面へ戻る', demos_schedule_path, class: 'a-back btn' %>
</div>

app/views/demos/search_words.html.erb
<h1>Demos#search_words</h1>
<p>Find me in app/views/demos/search_words.html.erb</p>

app/views/demos/update.html.erb
<h1>Demos#update</h1>
<p>Find me in app/views/demos/update.html.erb</p>