config/routes.rb
Rails.application.routes.draw do
  # devise_for :samples
  # devise_for :clients
  # devise_for :users
  devise_for :samples, controllers: {
    sessions:      'samples/sessions',
    passwords:     'samples/passwords',
    registrations: 'samples/registrations'
  }
  devise_for :clients, controllers: {
    sessions:      'clients/sessions',
    passwords:     'clients/passwords',
    registrations: 'clients/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  devise_scope :sample do
    post 'samples/guest_sign_in', to: 'samples/sessions#new_guest'
  end
  devise_scope :client do
    post 'clients/guest_sign_in', to: 'clients/sessions#new_guest'
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # root to: 'kototabis#index'
  resources :demos, only: [:index, :new, :edit, :update, :create, :destroy] do
    collection do
      get 'demos/list'
    end
  end
    get 'demos/home'
    get 'demos/about'
    get 'demos/show'
    get 'demos/schedule'
    get 'demos/search'
    get 'demos/search_words'

  resources :events do #管理画面用
    collection do
      get 'search_words'
      get 'events/search' 
    end
  end 

  resources :tops
    post 'products/add'
  resources :products do
    resources :points
    resources :itinerarys
    resources :events 
  end

  root to: 'demos#home'
end

app/models/top.rb
class Top < ApplicationRecord
  belongs_to :client, optional: true
  has_many :product  # , dependent: :destroy
  # Active Storage用アソシエーション
  has_one_attached :image
  # career wave用
  mount_uploader :video_top, VideoUploader
  validates :video_top, :client_id, presence: true
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @client = Client.find(current_client.id) # footer条件分岐のため。どのクライアントか特定する為にcurrent_client.id
    @top = Top.find_by(client_id: @client.id)
    # @products = Product.find(params[:id]) #top/indexでproductのデータを表示させる為。元々レンダーで_product.htmlを表示させる為の定義だった。
    @products = Product.where(client_id: @client.id) # top/indexでproductのデータを表示させる為。
  end

  def new
    @top = Top.new
  end

  def show
    @top = Top.find_by(client_id: params[:id])
    @products =  Product.where(client_id: params[:id])
    @client_id = params[:id]
    session['current.client_id'] = { client: @client_id }
    @client = Client.find(@client_id)
  end

  def create
    @top = Top.new(tops_params)
    if @top.save
      redirect_to new_product_path
    else
      render :new
    end
  end

  def edit
    @client = Client.find(current_client.id) # footer条件分岐のため
    @top = Top.find_by(client_id: @client.id) # データ取得（トップ動画再生と編集データ取得）
    @products = Product.where(client_id: @client.id) # top/indexでproductのデータを表示させる為。
  end

  def update
    top = Top.find(params[:id])
    top.update(tops_params)
    # if top.valid?
    redirect_to edit_top_path
    # else
    # end
  end

  def destroy
    @top = Top.find(params[:id])
    @top.destroy!
    redirect_to root_path
  end

  private

  def tops_params
    params.require(:top).permit(:video_top, :image, :title, :client_id).merge(client_id: current_client.id)
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/tops/create.html.erb
<h1>Tops#create</h1>
<p>Find me in app/views/tops/create.html.erb</p>
<%= link_to "続いて商品ページを作成する", new_product_path %>
<%= link_to "topに戻る", root_path %>

app/views/tops/destroy.html.erb
<h1>Tops#destroy</h1>

<h3>消去しました</h3>

<%=link_to '戻る', root_path, class:"" %>

app/views/tops/edit.html.erb
<div class="top-edit-wrap">
<!-----動画------>
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        <%= video_tag @top.video_top, class:"top_video", :loop => true, :autoplay => true, :muted => true %> 
        <div class="top_hero" >
          <%= image_tag @top.image, class: "top_logo" if @top.image.attached?  %>
          <h3 class="top_title"><%= @top.title %></h3>
        </div>
      </div>
    </div>
  </div>
<!------商品------>
  <div class="products-container container-fluid">
      <div class="row row-cols-3">
        <% @products.each do |product| %>
          <div class="products_hero col">
            <div class="hover-product">
              <%= link_to edit_product_path(product.id) do %>
                <%= image_tag product.image, class:"products_img" if product.image.attached?  %>
                <div class="products_info">
                  <p class="products_name"><%= product.name %></p>
                  <p class="products_text"><%= product.title %></p>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
  </div>
</div>

<!----------------ここからエディター---------------->
<div class="top-editor-wrap">
  <div id="app2">
    <!--メニューのボタン-->
    <div class="top-editor_btn" v-on:click='ActiveBtn=!ActiveBtn'>
      <%= image_tag "editor_logo.png", alt:"editor_logo", class:"img" %>
    </div>
    <!--サイドバー-->
    <transition name="editor-side">
      <div class="editor-side" v-show="ActiveBtn">
        <% if @top == nil %>
          <div class="top-new">
            <%= link_to "新規ページを作成する", new_top_path %>
          </div>
            <% else %>
          <div class="top-editor-said">
            <%#= link_to "top画面を編集する", edit_top_path(@top.id) %>
            <div class="edit-top">
              <h3>トップ画面編集</h3>
              <%= form_with model: @top, local: true do |f| %>
                <% render 'shared/error_messages', model: f.object %>
                <div class="top-editor-video-box">
                  <p class="editor-title"><%= f.label :動画 %></p>
                  <%= f.file_field :video_top, :accept => 'video/*' %>
                </div>
                <div class="top-editor-logo-box">
                  <p class="editor-title"><%= f.label :ロゴ %></p>
                  <%= f.file_field :image %>
                </div>
                <div class="top-editor-title-box">
                  <p class="editor-title"><%= f.label :タイトル %></p>
                  <%= f.text_field :title %>
                </div>
                <div class="top-editor-submit-box">
                  <%= f.submit "編集する", class:"top-editor-submit" %>
                </div>
              <% end %>
            </div>

            <div class="add-product">
              <h3>商品追加</h3>
              <%= form_with model: @product, url:products_add_path, local: true do |f| %>
                <%#= render 'shared/error_messages', model: f.object %>
                <div>
                  <p><%= f.label :画像 %><span class="require">*</span></p>
                  <%= f.file_field :image %>
                </div>
                <div>
                  <p><%= f.label :商品名 %><span class="require">*</span></p>
                  <%= f.text_field :name, placeholder:"例) 京都ツアー" %>
                </div>
                <div>
                  <p><%= f.label :サブタイトル %></p>
                  <%= f.text_field :title, placeholder:"例) 京都を歩く" %>
                </div>
                <div>
                  <p><%= f.label :紹介文 %></p>
                  <%= f.text_area :text %>
                </div>
                <div>
                  <p><%= f.label :金額 %><span class="require">*</span></p>
                  <%= f.text_field :price, placeholder:"例) 10,000" %>
                </div>
                <div>
                  <p><%= f.label :単位 %><span class="require">*</span></p>
                  <%= f.text_field :unit, placeholder:"例) 人" %>
                </div>
                <%= f.submit "作成する", class:"#" %>
              <% end %>
            </div>
              <%#= button_to "「@top.tilleのサイト」を削除する", top_path(@top.id), method: :delete %>
          </div>
        <% end %>
      </div>
    </transition>
  </div><%#app%>
</div>

<%= render "shared/footer_client" %>
<%= javascript_pack_tag 'menu_vue' %>

app/views/tops/index.html.erb
<div class="top">
  <!----動画----->
  <div class="top_video_content" >
    <% if @top == nil %>
      <div class="container-fluid">
        <div class="row">
          <div class="col">
            <%= video_tag("/", class: "top_video", controls: true, alt:"ダミー") %> 
            <%= link_to new_top_path do %>
              <div class="top_ziza" >
                <h3 class="top_title">サイトを作成する</h3>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% else %>
      <div class="container-fluid">
        <div class="row">
          <div class="col">
            <%= video_tag @top.video_top, class:"top_video", :loop => true, :autoplay => true, :muted => true %> 
            <div class="top_hero" >
              <%#= image_tag @top.image, :size =>"230×270", class: "top_logo" if @top.image.attached? %>
              <h3 class="top_title"><%= @top.title %></h3>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <!----商品----->
  <div class="products-container container-fluid">
    <div class="row row-cols-3">
      <% @products.each do |product| %>
        <div class="products_hero col">
          <div class="hover-product">
            <%= link_to products_path(product.id) do %>
              <%= image_tag product.image, class:"products_img" if product.image.attached?  %>
              <div class="products_info">
                <p class="products_name"><%= product.name %></p>
                <p class="products_text"><%= product.title %></p>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <%= render "shared/footer_client" %>
</div>


<%= javascript_pack_tag 'menu_vue' %>

app/views/tops/new.html.erb
<%= render "shared/header" %>

<div class="top-new-wrap">
  <div class="top-contents-row">
    <div class="top-new">
      <h3>トップ画面作成</h3>
        <%= form_with model: @top, local: true do |f| %>
          <%= render 'shared/error_messages', model: f.object %>
          <div class="top-field">
            <div class="top-new-field">
              <p class="editor-title-new"><%= f.label :動画 %><span class="require">*</span></p>
              <%= f.file_field :video_top, :accept => 'video/*' %>
            </div>
            <div class="top-new-field">
              <p class="editor-title-new"><%= f.label :ロゴ %><span>（サイズ230×270推奨）</span></p>
              <%= f.file_field :image %>
            </div>
            <div class="top-new-field">
              <p class="editor-title-new"><%= f.label :タイトル %></p>
              <%= f.text_field :title, class:"top-new-field-input" %>
            </div>
            <div class="top-new-field">
              <%= f.submit "作成する", class:"top-new-submit" %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

<%= render "shared/footer_logo" %>

app/views/tops/show.html.erb
<div class="top">
  <!--------メニュー--------->
  <div class="menu-wrap">
    <div id="app1">
      <div class="hamburger_btn" v-on:click='ActiveBtn=!ActiveBtn'>
        <span class="line line_01" v-bind:class="{'btn_line01':ActiveBtn}"></span>
        <span class="line line_02" v-bind:class="{'btn_line02':ActiveBtn}"></span>
        <span class="line line_03" v-bind:class="{'btn_line03':ActiveBtn}"></span>
      </div>
      <!--サイドバー-->
      <transition name="menu">
        <div class="menu" v-show="ActiveBtn">
          <div class='user-conf' >
            <% if user_signed_in? %>
              <div class="user-sin-login">
                <p><%#= link_to current_user.name, edit_user_registration_path  %></p>
                <p><%= link_to current_user.name  %></p>
                <p><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></p>
                <%#= link_to '予約状況を見る', event_path, class: "#" %>
              </div>
              <% else %>
              <div class="user-sin-login">
                <p>
                  <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post %>
                </p>
                <p>
                  <%= link_to "新規登録する", new_user_registration_path %>
                </p>
                <p>
                  <%= link_to "ログイン", new_user_session_path %>
                </p>
              </div>
            <% end %>
          </div>
          <!----サイドバー商品名----->
          <div class="product">
            <% @products.each do |product|  %>
              <ul>
                <li>
                  <%= link_to products_path(product.id) do %>
                    <%= product.name %>
                  <% end %>
                </li>
              </ul>
            <% end %>
          </div>
        </div>
      </transition>
    </div>
  </div>
  <!----動画----->
  <div class="top_video_content" >
    <% if @top == nil %>
      <div class="container-fluid">
        <div class="row">
          <div class="col">
            <%= video_tag("/", class: "top_video", controls: true, alt:"ダミー") %> 
            <%= link_to new_top_path do %>
              <div class="top_ziza" >
                <h3 class="top_title">サイトを作成する</h3>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% else %>
      <div class="container-fluid">
        <div class="row">
          <div class="col">
            <%= video_tag @top.video_top, class:"top_video", :loop => true, :autoplay => true, :muted => true %> 
            <div class="top_hero" >
              <%= image_tag @top.image, :size =>"230×270", class: "top_logo" if @top.image.attached? %>
              <h3 class="top_title"><%= @top.title %></h3>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <!----商品----->
  <div class="products-container container-fluid">
    <div class="row row-cols-3">
      <% @products.each do |product| %>
        <div class="products_hero col">
          <div class="hover-product">
            <%= link_to products_path(product.id) do %>
              <%= image_tag product.image, class:"products_img" if product.image.attached?  %>
              <div class="products_info">
                <p class="products_name"><%= product.name %></p>
                <p class="products_text"><%= product.title %></p>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <!------フッター------>
<%= render "shared/footer_user" %>
</div>


<%= javascript_pack_tag 'menu_vue' %>

app/views/tops/update.html.erb
<h1>Tops#update</h1>

  <!--------topのメニュー--------->
  <% if client_signed_in? %>
        <div class="menu-wrap">
      <div id="app1">
        <!--メニューのボタン-->
        <div class="hamburger_btn" v-on:click='ActiveBtn=!ActiveBtn'>
          <span class="line line_01" v-bind:class="{'btn_line01':ActiveBtn}"></span>
          <span class="line line_02" v-bind:class="{'btn_line02':ActiveBtn}"></span>
          <span class="line line_03" v-bind:class="{'btn_line03':ActiveBtn}"></span>
        </div>
        <!--サイドバー-->
        <transition name="menu">
          <div class="menu" v-show="ActiveBtn">
            <div class='user-conf' >
                <div class="user-sin-login">
                  <p>
                    <%#= link_to '作成中', top_path, method: :post %>
                  </p>
                  <p>作成中</p>
                </div>
            </div>
          </div>
        </transition>
      </div>
    </div>
  <% else %>
    <div class="menu-wrap">
      <div id="app1">
        <!--メニューのボタン-->
        <div class="hamburger_btn" v-on:click='ActiveBtn=!ActiveBtn'>
          <span class="line line_01" v-bind:class="{'btn_line01':ActiveBtn}"></span>
          <span class="line line_02" v-bind:class="{'btn_line02':ActiveBtn}"></span>
          <span class="line line_03" v-bind:class="{'btn_line03':ActiveBtn}"></span>
        </div>
        <!--サイドバー-->
        <transition name="menu">
          <div class="menu" v-show="ActiveBtn">
            <div class='user-conf' >
              <% if user_signed_in? %>
                <div class="user-sin-login">
                  <p><%#= link_to current_user.name, edit_user_registration_path  %></p>
                  <p><%= link_to current_user.name  %></p>
                  <p><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></p>
                  <%#= link_to '予約状況を見る', event_path, class: "#" %>
                </div>
                <% else %>
                <div class="user-sin-login">
                  <p>
                    <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post %>
                  </p>
                  <p>
                    <%= link_to "新規登録する", new_user_registration_path %>
                  </p>
                  <p>
                    <%= link_to "ログイン", new_user_session_path %>
                  </p>
                </div>
              <% end %>
            </div>
            <!----サイドバー商品名----->
            <div class="プロダクト">
              <% @products.each do |product|  %>
                <ul>
                  <li>
                    <%= link_to products_path(product.id) do %>
                      <%= product.name %>
                    <% end %>
                  </li>
                </ul>
              <% end %>
            </div>
          </div>
        </transition>
      </div>
    </div>
  <% end %>