config/routes.rb
Rails.application.routes.draw do
  # devise_for :samples
  # devise_for :clients
  # devise_for :users
  devise_for :samples, controllers: {
    sessions:      'samples/sessions',
    passwords:     'samples/passwords',
    registrations: 'samples/registrations'
  }
  devise_for :clients, controllers: {
    sessions:      'clients/sessions',
    passwords:     'clients/passwords',
    registrations: 'clients/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  devise_scope :sample do
    post 'samples/guest_sign_in', to: 'samples/sessions#new_guest'
  end
  devise_scope :client do
    post 'clients/guest_sign_in', to: 'clients/sessions#new_guest'
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # root to: 'kototabis#index'
  resources :demos, only: [:index, :new, :edit, :update, :create, :destroy] do
    collection do
      get 'demos/list'
    end
  end
    get 'demos/home'
    get 'demos/about'
    get 'demos/show'
    get 'demos/schedule'
    get 'demos/search'
    get 'demos/search_words'

  resources :events do #管理画面用
    collection do
      get 'search_words'
      get 'events/search' 
    end
  end 

  resources :tops
    post 'products/add'
  resources :products do
    resources :points
    resources :itinerarys
    resources :events 
  end

  root to: 'demos#home'
end

app/models/event.rb
class Event < ApplicationRecord
  attr_accessor :token

  belongs_to :user, optional: true
  belongs_to :client, optional: true
  belongs_to :product, optional: true
  # モジュールを取り込む記述
  extend ActiveHash::Associations::ActiveRecordExtensions
  # アクティブハッシュ用アソシエーション
  belongs_to_active_hash :num

  # バリデーション
  validates :token, presence: true, on: :create
  validates :start_time, presence: true
  validates :num_id, presence: true, numericality: { other_than: 0 }
  validates :price, presence: true, numericality: { other_than: 0 }

  # <ワード検索時の処理>
  def self.search(search)
    if search != ''
      Event.where('price LIKE(?)', "%#{search}%")
    else
      Event.all
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :search_event, only: [:index, :search, :show]

  def index
    # set_event_column
    @events = Event.where(client_id: current_client.id)
    @event_name = @events.select('product_name').distinct # Eventではなく@eventsとする事でプルダウンでログイン中のクライアントのデータのみ取得
    @top = Top.find_by(params[:id]) # 条件分岐のため
  end

  def new
    @user = User.find(current_user.id)
    @event = Event.new(event_params)
    @product = Product.find(params[:product_id])
    @client_id = @product.client_id # 条件分岐の為
    @client = Client.find(@client_id) # 条件分岐の為
  end

  def create
    @product = Product.find(params[:product_id])
    @event = Event.new(event_create_params)
    if @event.valid?
      pay_item
      @event.save
    else
      render :new
    end
    @top = Top.find_by(params[:id]) # footer条件分岐のため
  end

  def show
    # @e = Event.ransack(params[:q])
    @event = Event.find_by(id: params[:id])
    @results = @e.result # .includes(:event)
  end

  def edit
    @event = Event.find(params[:id])
    @client = Client.find_by(params[:id]) # footer条件分岐のため
    # @user = User.where()
    # @product = Product.all
  end

  def update
    event = Event.find(params[:id])
    event.update(event_edit_params)
    redirect_to edit_event_path(event.id)
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    redirect_to events_path
  end

  def search_words
    @client = Client.find_by(params[:id]) # footer条件分岐のため
    @events = Event.search(params[:keyword])
    # @users = User.search(params[:keyword])
    # binding.pry
  end

  def search
    @client = Client.find_by(params[:id]) # footer条件分岐のため
    # @e = Event.ransack(params[:q])
    @results = @e.result # .includes(:event)
  end

  private

  def event_params
    @product = Product.find(params[:product_id])
    params.permit(:user_name, :user_kana, :user_email, :user_tel, :product_name, :price, :num_id, :start_time, :product_id)
          .merge(user_id: current_user.id, client_id: @product.client_id)
  end

  def event_create_params
    @product = Product.find(params[:product_id])
    params.require(:event).permit(:user_name, :user_kana, :user_email, :user_tel, :product_name, :price, :num_id, :start_time, :product_id)
          .merge(user_id: current_user.id, client_id: @product.client_id, token: params[:token])
  end

  def event_edit_params
    params.require(:event).permit(:user_name, :user_kana, :user_email, :user_tel, :product_name, :price, :num_id, :start_time, :product_id)
          .merge(user_id: current_user.id, client_id: current_client.id)
  end

  def pay_item
    Payjp.api_key = ENV['PAYJP_SECRET_KEY'] # 環境変数に入れて呼び込む
    Payjp::Charge.create(
      amount: @event.price,
      card: event_create_params[:token], # カードトークン
      currency: 'jpy' # 通貨の種類(日本円)
    )
  end

  def search_event
    @e = Event.ransack(params[:q])
  end

  # 重複をなくす
  def set_event_column
    @event_name = Event.select('product_name').distinct
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/create.html.erb
<%= render "shared/header_user" %>
<div class="done-wrap">
    <div class="done-container">
      <div class="done-box">
        <h1>ご予約完了しました。</h1>
        <p>ありがとうございます。<br>
          ご予約が完了しました。<br>
          確認のメールをお送りしましたので、予約内容を必ずご確認ください。
        </p>
        <div class="back-container">
          <div class="back-container-box">
            <%= link_to "トップへ戻る", top_path(@product.client_id), class:"btn btn-default back-button" %>
          </div>
        </div>
      </div>
    </div>
</div>
<%# <div class="footer-logo-box">
  <img src="/assets/footer-logo.png" alt="footer-logo.png" class="footer-logo">
</div> %>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

<h1>削除しました</h1>

  <div class="">
    <%= link_to "戻る", root_path%>
  </div>

app/views/events/edit.html.erb
<%= render "shared/header" %>

<div class="edit-wrap">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">名前</th>
        <th scope="col">人数</th>
        <th scope="col">商品名</th>
        <th scope="col">金額</th>
        <th scope="col">参加日</th>
        <th scope="col">Email</th>
        <th scope="col">TEL</th>
        <th scope="col">オプション</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
    <tr>
      <%= form_with(model: @event, local: true) do |f| %>
        <tr>
          <td><%= f.text_field :user_name %></td>
          <td><%= f.collection_select(:num_id, Num.all, :id, :name, {}, {class:"#", id:"#"}) %></td>
          <td><%= f.text_field :product_name %></td>
          <td><%= f.text_field :price %></td>
          <td><%= f.text_field :start_time %></td>
          <td><%= f.text_field :user_email %></td>
          <td><%= f.text_field :user_tel %></td>
          <td><%= f.submit "保存する" %></td>
      <% end %>
          <td><%= button_to "削除する", event_path(@event.id), method: :delete, class:"#" %></td>
        </tr>
    </tr>
    </tbody>
    <br>
  </table>
  <%= link_to '管理画面へ戻る', events_path, class: 'a-back btn' %>
</div>

app/views/events/index.html.erb
<%= render "shared/header" %>

<div class="schedule">
  <div class="search">
      <div class="search-data">
      <h3>日付検索</h3>
      <%= search_form_for @e, url: events_search_events_path do |f| %>
        <%= f.label :product_name_eq, '商品名検索' %>
        <%= f.collection_select :product_name_eq, @event_name, :product_name, :product_name,  include_blank: '指定なし' %>
        <%= f.submit '検索' %>
      <% end %>
    </div>
    <div class="search-name">
      <%# <h3>名前検索</h1> %>
      <%#= form_with(url: search_words_events_path, local: true, method: :get, class: "#") do |form| %>
        <%# <label>名前</label> %>
        <%#= form.text_field :keyword, placeholder: "名前で検索する", class: "#" %>
        <%#= form.submit "検索", class: "#" %>
      <%# end %>
    </div>
  </div>

  <!---カレンダー-->
  <%= month_calendar events: @events do |date, events| %>
    <%= date.day %>

  <!----イベントー---->
    <ul class="event-list">
      <% events.each do |event| %>
      <li class="list">
        <%= link_to edit_event_path(event.id) do %>
          <%= event.user_name %>
          <%= event.num.name %><span>人</span>
          <%= event.product_name %>
        <% end %>
      </li>
    </ul>
    <% end %>
  <% end %>
</div>

<%= render "shared/footer_client" %>

app/views/events/new.html.erb
<%= render "shared/header_user" %>
テスト
<div class="conf-wrap">
  <div class="conf-container container">
    <div class="conf-content">
      <div class="pay-content">
        <%= form_with model: @event, url:product_events_path, id: 'charge-form', local: true do |f| %>
          <%= render 'shared/error_messages', model: f.object %>
          <%= f.hidden_field :user_name, value:current_user.name %>
          <%= f.hidden_field :user_kana, value:current_user.kana %>
          <%= f.hidden_field :user_email, value:current_user.email %>
          <%= f.hidden_field :user_tel, value:current_user.tel %>
          <%= f.hidden_field :product_name, value:@product.name %>
          <%= f.hidden_field :num_id, value:@event.num.id %>
          <%= f.hidden_field :start_time, value:@event.start_time %>
          <%= f.hidden_field :price, value:@event.price %>
          <%= f.hidden_field :product_id, value:@product.id %>
          <%# 決済機能 %>
          <div class='pay-form-box'>
            <h1>お支払い</h1>
            <div class='pay-form'>
              <div class='card-num'>
                <h4>カード番号</h4>
                <%= f.text_field :number, class:"input-expiration-number", id:"number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
              </div>
              <div class='input-expiration-date-wrap'>
                <h4>有効期限</h4>
                <div class="input-expiration-date-box">
                  <li><%= f.text_field :exp_month, class:"input-expiration-date", id:"exp_month", placeholder:"例)1" %><span class="expiration-date">月</span></li>
                  <li><%= f.text_field :exp_year, class:"input-expiration-date", id:"exp_year", placeholder:"例)24" %><span class="expiration-date">年</span></li>
                </div>
              </div>
              <div class="input-expiration-s">
                <h4>セキュリティコード</h4>
                <%= f.text_field :cvc, class:"input-cvc", id:"cvc", placeholder:"カード背面の番号", maxlength:"3" %>
              </div>
              <div class='pay-button'>
                <p><%= f.submit "予約する", class:"pay-submit" %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="conf-title-box">
        <h1>内容の確認</h1>
        <div class="conf-title">
          <p>名前: <%= current_user.name %>様</p>
          <p>商品名: <%= @product.name %></p>
          <p>参加人数: <%= @event.num.name %></p>
          <p>ご希望日: <%= @event.start_time %></p>
          <p>合計金額: ¥<span><%= @event.price %></span></p>
        </div>
      </div>
    </div>
  </div>
  <%= render "shared/footer_user" %>
</div>

app/views/events/search.html.erb
<%= render "shared/header" %>

<!-----ヘッター----->
<div class="header-wrap">
  <div class="header-main">
    <div class="header-logo-box">
      <%= link_to image_tag("/assets/header-logo"), demos_path%>
    </div>
    <div class="header-menu">
    </div>
  </div>
</div>

<div class="edit-wrap">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">商品名</th>
        <th scope="col">参加日</th>
        <th scope="col">名前</th>
        <th scope="col">カナ</th>
        <th scope="col">人数</th>
        <th scope="col">金額</th>
        <th scope="col">Email</th>
        <th scope="col">TEL</th>
        <th scope="col">予約日</th>
        <th scope="col">オプション</th>
      </tr>
    </thead>
    <tbody>
    <tr>
      <h1>検索結果</h1>
      <% if @results.length !=0 %>
        <% @results.each do |result| %>
        <tr>
          <td><%= result.id %></td>
          <td><%= result.product_name %></td>
          <td><%= result.start_time %></td>
          <td><%= result.user_name %></td>
          <td><%= result.user_kana %></td>
          <td><%= result.num_id %></td>
          <td><%= result.price %></td>
          <td><%= result.user_email %></td>
          <td><%= result.user_tel %></td>
          <td><%= result.created_at %></td>
          <td><%= button_to "編集", edit_event_path(result.id), method: :get, class:"search-edit-button" %></td>
      <% end %>
      <% else %>
        該当しません
      <% end %>
    </tr>
    </tbody>
    <br>
  </table>
  <%= link_to '管理画面へ戻る', events_path, class: 'a-back btn' %>
</div>

app/views/events/search_words.html.erb
<h1>名前検索結果</h1>

<%# if @users == nil %>
<% if @evens == nil %>
<p>検索結果はありません</p>
  <% else %>
    <% @events.each do |event| %>
    <%# @users.each do |user| %>
        <%#= user.name %>
        <%= event.name %>
      <%= link_to "編集", edit_event_path(event.id) %>
    <% end %>
<% end %>

app/views/events/show.html.erb
<%= render "shared/header" %>

<div class="search-wrap">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">.id</th>
        <th scope="col">名前</th>
        <th scope="col">人数</th>
        <th scope="col">商品名</th>
        <th scope="col">Email</th>
        <th scope="col">TEL</th>
        <th scope="col">オプション</th>
      </tr>
    </thead>
    <tbody>
    <tr>
      <% @results.each do |result| %>
        <tr>
          <th scope="row"><%= result.id %></th>
          <td><%= result.user_name %></td>
          <td><%= result.num_id %></td>
          <td><%= result.product_name %></td>
          <td><%= result.user_email %></td>
          <td><%= result.user_tel %></td>
          <td><%= button_to "編集", edit_event_path(result.id), method: :get, class:"search-edit-button" %></td>
        </tr>
      <% end %>
    </tr>
    </tbody>
    <br>
  </table>
  <%= link_to '管理画面へ戻る', events_path, class: 'a-back btn' %>
</div>